//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Holes = new HashSet<Hole>();
        }
    
        public int FacilityId { get; set; }
        public string Course_Name { get; set; }
        public int CourseId { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<Hole> Holes { get; set; }
    }
}
