//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golfer
    {
        public Golfer()
        {
            this.RoundDetails = new HashSet<RoundDetail>();
        }
    
        public int GolferId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Handicap_Index { get; set; }
    
        public virtual ICollection<RoundDetail> RoundDetails { get; set; }
    }
}
