//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfTrackerEntities1 : DbContext
    {
        public GolfTrackerEntities1()
            : base("name=GolfTrackerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Course> Courses { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<Golfer> Golfers { get; set; }
        public DbSet<Hole> Holes { get; set; }
        public DbSet<RoundDetail> RoundDetails { get; set; }
        public DbSet<TeeType> TeeTypes { get; set; }
    }
}
