//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundDetail
    {
        public int GolferId { get; set; }
        public int FacilityId { get; set; }
        public int CourseId { get; set; }
        public int TeeTypeId { get; set; }
        public int HoleId { get; set; }
        public double Differential { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public short Score { get; set; }
        public byte Putts { get; set; }
        public Nullable<bool> GIR { get; set; }
        public Nullable<bool> FIR { get; set; }
        public Nullable<byte> Up_And_Down { get; set; }
        public Nullable<byte> Par_Save { get; set; }
        public Nullable<byte> Sand_Save { get; set; }
        public Nullable<int> Driving_Distance { get; set; }
        public Nullable<int> Proximity { get; set; }
        public Nullable<double> Green_Fee { get; set; }
        public int RoundId { get; set; }
    }
}
