//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeeType
    {
        public TeeType()
        {
            this.Holes = new HashSet<Hole>();
            this.RoundDetails = new HashSet<RoundDetail>();
        }
    
        public int TeeTypeId { get; set; }
        public int FacilityId { get; set; }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Slope { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Gender { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Hole> Holes { get; set; }
        public virtual ICollection<RoundDetail> RoundDetails { get; set; }
    }
}
